apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-project2
  labels:
    app: my-web-app-project2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app-project2
  template:
    metadata:
      labels:
        app: my-web-app-project2
    spec:
      containers:
      - name: my-web-app-container
        image: 637423519309.dkr.ecr.us-west-2.amazonaws.com/webapp:latest
        ports:
        - containerPort : 5002
          protocol : TCP
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: project2-config
                key: RDS_HOST
      
          - name: RDS_NAME
            valueFrom:
              configMapKeyRef:
                name: project2-config
                key: RDS_NAME
          - name: RDS_USER
            valueFrom:
              secretKeyRef:
                name: project2-secret
                key: RDS_USER
          - name: RDS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: project2-secret
                key: RDS_PASSWORD
---

apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service-project2
  labels:
    app: my-web-app-project2
spec:
  selector:
    app: my-web-app-project2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: LoadBalancer


