apiVersion: v1
kind: Secret
metadata:
  name: project2-secret
type: Opaque
data:
  DB_USER: d2ViYXBw    # base64 encoded value of 'my_user'
  DB_PASSWORD: cGFzc3dvcmQ=    # base64 encoded value of 'secret_password'
